export const env = {
  //  URL: "http://app.washup.com.pk/",
  URL: "https://dev.washup.com.pk/",
  api_login: "api/login",
  api_logout: "api/logout",
  api_forgot: "api/forgot",
  api_meterPhoto: "api/store_reading",
  api_dashboard: "api/dashboard",
  api_todayrides: "api/myrides",
  api_pickup: "api/pickup",
  api_dropoff: "api/dropoff",
  api_pickdrop: "api/pickdrop",
  api_payment: "api/payment",
  api_riderhistory: "api/riderhistory",
  api_confirmpickupservice: "api/store_items",
  api_confirmpickup: "api/confirmpickup",
  api_addanotherorder: "api/addanotherorder",
  api_ordercancel:"api/noMoreOrder",
  api_cancel: "api/cancel",
  api_collectpayment: "api/paymentonlyrides",
  api_collectpaymentsubmit: "api/paymentonlyridessubmit",
  api_recentorders: "api/recent_orders",
  api_daystatus: "api/day_status",
  api_movetohub: "api/move_to_hub",
  api_report: "api/report",
};
